name: test

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  go-test:
    uses: ./.github/workflows/go-test.yml
