name: test

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  rust-test:
    uses: ./.github/workflows/rust-test.yml
